import pygame


class Constants:
    BLOCK_HEIGHT = 40
    BLOCK_WIDTH = 40

    BOARD_WIDTH = 10
    BOARD_HEIGHT = 20
    SCREEN_WIDTH = BOARD_WIDTH * BLOCK_WIDTH + 480
    SCREEN_HEIGHT = BOARD_HEIGHT * BLOCK_HEIGHT

    MAX_LEVEL = 15

    AUTO_REPEAT_DELAY_MS = 300
    LOCKDOWN_DELAY_MS = 500

    FALL_EVENT = pygame.USEREVENT + 1
    LOCKDOWN_EVENT = pygame.USEREVENT + 2
    LEFT_AUTO_REPEAT_EVENT = pygame.USEREVENT + 3
    RIGHT_AUTO_REPEAT_EVENT = pygame.USEREVENT + 4
